#pragma once

// C
#include <cassert>
#include <cstdio>
#include <cmath>
#include <ctime>
#include <cstdlib>
#include <cstdarg>
#include <string>
#include <chrono>
// STL
#include <vector>
#include <stack>
#include <queue>
#include <deque>
#include <map>
#include <set>
#include <string>
#include <fstream>
#include <memory>
#include <mutex>
#include <atomic>
#include <thread>
#include <optional>
#include <unordered_set>
#include <unordered_map>
#include <functional>
#include <filesystem>
#include <condition_variable>
// Math
#include "Math.h"
#include "Vec3.h"
#include "Vec4.h"
#include "Quat.h"
#include "Mat3.h"
#include "Mat4.h"